# Generated by Django 5.1 on 2024-10-07 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_likes_alter_follow_id_alter_like_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='author',
            new_name='liker',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
