# Generated by Django 5.1 on 2024-10-07 01:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_rename_author_like_liker_remove_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
