# Generated by Django 5.1.2 on 2024-10-14 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_user_followers_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follower_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
