# Generated by Django 5.1.2 on 2025-01-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_remove_user_followers_remove_user_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
